spring:
  datasource:
    url: jdbc:h2:./database
    username: sa
    password:
#  datasource:
#    url: jdbc:postgresql://127.0.0.1:5432/report_builder
#    username: postgres
#    password: password

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none